title: Michel Isamuna N.
logo: "/images/myself.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Information Management, Software Developer, GIS Specialist & Data Scientist.
  <br><br>
  Motivated, a team player with a sense of responsibility, with extensive experience in improving the understanding of information and data.
  <br><br>
  <a href="https://www.linkedin.com/in/michelo243/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
